name: docker

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

env:
  TRIVY_VERSION: v0.68.2

jobs:
  docker:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # to retrieve git tags
      # How to set system path variable in github action workflow: https://stackoverflow.com/a/68214331
      - name: Add to PATH
        shell: bash
        run: |
          echo "/home/runner/bin" >> "$GITHUB_PATH"
      # FIXME: issue #44
      # - name: Install Trivy
      #   uses: aquasecurity/setup-trivy@v0.2.5
      #   with:
      #     version: ${{ env.TRIVY_VERSION }}
      - name: Run CI tests for Docker
        working-directory: ./src/python
        shell: bash
        run: |
          make ci-test-docker TOOLS_DIR="/home/runner/bin"
