name: docker

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

env:
  TRIVY_VERSION: v0.69.2

jobs:
  docker:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # to retrieve git tags
      # How to set system path variable in github action workflow: https://stackoverflow.com/a/68214331
      - name: Add to PATH
        shell: bash
        run: |
          echo "/home/runner/bin" >> "$GITHUB_PATH"
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514
        with:
          version: ${{ env.TRIVY_VERSION }}
          cache: true
      - name: Run CI tests for Docker
        working-directory: ./src/python
        shell: bash
        run: |
          make ci-test-docker TOOLS_DIR="/home/runner/bin"
